# version: "3.8"

# services:
#   # PostgreSQL Database
#   postgres:
#     image: postgres:15-alpine
#     container_name: task_manager_db_dev
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: taskdb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - postgres_data_dev:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d taskdb"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   # Redis Cache
#   redis:
#     image: redis:7-alpine
#     container_name: task_manager_redis_dev
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 3

# volumes:
#   postgres_data_dev:
#     driver: local

version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: task_manager_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: task_manager_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_dev:
    driver: local
